export const ADD_NEW_POST = 'ADD_NEW_POST';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_SUCCESS = ' GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = ' GET_ALL_POSTS_FAIL';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';

export const ADD_NEW_REPLY = 'ADD_NEW_REPLY';
export const ADD_NEW_REPLY_SUCCESS = 'ADD_NEW_REPLY_SUCCESS';
export const ADD_NEW_REPLY_FAIL = 'ADD_NEW_REPLY_FAIL';
